--[[
Tree of Thoughts Agent - Complete Implementation

Requirements:
- Use real tree of thought pattern with deliberate reasoning
- Explore multiple solution paths and find the best one
- Create well-defined task lists as result of reasoning
- Access all available tools in the plugin
- General purpose agent (not domain-specific)
- Workflow: User prompt → Tree of Thoughts Analysis → Plan Creation → Execution → Reflection

Design:
The agent operates in three modes:
1. REASON: Generate N thought processes, evaluate each, select best approach
2. EXECUTE: Implement the selected plan step by step
3. REFLECT: Analyze results and refine plan using tree of thoughts

--]]

local config = require("codecompanion.config")
local log = require("codecompanion.utils.log")
local utils = require("codecompanion.utils")

local fmt = string.format
-- Helper function for output formatting
local function generate_analysis_summary(analysis)
  if not analysis.meta_analysis then
    return "Multiple approaches analyzed and evaluated"
  end

  local meta = analysis.meta_analysis
  return fmt(
    "- Diversity: %s\n- Coverage: %s\n- Reasoning: %s",
    meta.diversity_score or "Good",
    meta.coverage_analysis or "Comprehensive",
    meta.recommendation and meta.recommendation.reasoning or "Best approach selected"
  )
end

-- ============================================================================
-- UTILITY FUNCTIONS (Implementations would be expanded)
-- ============================================================================

local function extract_key_terms(text)
  local terms = {}
  for word in text:gmatch("%w+") do
    if #word > 3 then
      table.insert(terms, word)
    end
  end
  return table.concat(terms, " ")
end

local function generate_filename(step, plan)
  local base = step.action:gsub("%W", "_"):lower()
  return fmt("step_%d_%s.lua", step.step_number, base)
end

local function generate_file_content(step, plan)
  return fmt(
    [[-- Generated by Tree of Thoughts Agent
-- Plan: %s
-- Step %d: %s
-- Task: %s

-- TODO: Implement %s
]],
    plan.id,
    step.step_number,
    step.action,
    plan.task,
    step.description
  )
end

local function generate_code_content(step, plan)
  return fmt("-- Step %d: %s\n-- TODO: Implement this step", step.step_number, step.description)
end

local function generate_command(step, plan)
  if step.action:match("test") then
    return "echo 'Testing step: " .. step.description .. "'"
  else
    return "echo 'Executing: " .. step.description .. "'"
  end
end

-- Placeholder implementations for reflection functions
local function analyze_performance_issues(plan)
  return {}
end
local function analyze_completeness_gaps(plan)
  return {}
end
local function analyze_innovation_potential(plan)
  return {}
end
local function generate_performance_refinements(plan)
  return {}
end
local function generate_completeness_refinements(plan)
  return {}
end
local function generate_innovation_refinements(plan)
  return {}
end
local function select_best_reflection(approaches)
  return approaches[1]
end
local function calculate_reflection_confidence(reflection)
  return 0.8
end
local function apply_plan_refinements(plan, refinements)
  return 0
end

---Generate example tree of thoughts (simulates LLM response)
local function generate_example_tree_of_thoughts(task, available_tools, num_thoughts)
  return {
    thought_processes = {
      {
        id = "systematic_approach",
        name = "Systematic Analysis",
        description = "Break down the problem systematically and solve step by step",
        reasoning_chain = {
          {
            branch = "problem_analysis",
            thoughts = { "What are the key requirements?", "What constraints exist?" },
            conclusion = "Need structured approach to handle complexity",
          },
        },
        steps = {
          {
            step_number = 1,
            action = "analyze_requirements",
            tools = { "grep_search", "file_search" },
            description = "Understand the problem requirements",
            expected_outcome = "Clear understanding of what needs to be built",
          },
        },
        evaluation = {
          feasibility = 0.9,
          completeness = 0.8,
          tool_fit = 0.9,
          innovation = 0.6,
          risk_level = 0.2,
        },
        confidence = 0.85,
        risks = { "May be slow" },
        mitigations = { "Set time limits" },
      },
    },
    meta_analysis = {
      diversity_score = "High diversity across approaches",
      coverage_analysis = "Covers most aspects of the problem",
      recommendation = {
        best_approach_id = "systematic_approach",
        reasoning = "Most reliable approach with good tool fit",
        confidence = 0.85,
        backup_approach = "None in this example",
      },
    },
  }
end

-- ============================================================================
-- DATA STRUCTURES
-- ============================================================================

local AgentState = {}
AgentState.__index = AgentState

function AgentState.new()
  return setmetatable({
    active_plans = {},
    reasoning_sessions = {},
    execution_logs = {},
    reflection_results = {},
  }, AgentState)
end

-- ============================================================================
-- CORE TREE OF THOUGHTS FUNCTIONS
-- ============================================================================

---Generate a comprehensive tree of thoughts prompt for the LLM
---@param task string The problem to solve
---@param available_tools string[] List of available tools
---@param num_thoughts number Number of thought processes to generate
---@return string The prompt for LLM
local function create_tree_of_thoughts_prompt(task, available_tools, num_thoughts)
  local tools_str = table.concat(available_tools, ", ")

  return fmt(
    [[
You are an expert problem-solver using Tree of Thoughts reasoning. Your task is to generate %d completely different approaches to solve this problem.

PROBLEM: %s
AVAILABLE TOOLS: %s

For each approach, think like a different expert would:
- Approach 1: Think like a systematic methodical expert
- Approach 2: Think like a creative innovative expert
- Approach 3: Think like a risk-averse careful expert
- Approach 4: Think like a rapid prototyping expert
(Continue this pattern for additional approaches)

For EACH approach, provide:

1. UNIQUE PERSPECTIVE: What makes this approach fundamentally different?

2. REASONING CHAIN: Develop your thinking through these branches:
   - PROBLEM ANALYSIS: What are the core challenges?
   - SOLUTION EXPLORATION: What are possible ways to solve this?
   - IMPLEMENTATION STRATEGY: How would you actually do it?
   - SUCCESS VALIDATION: How would you know it worked?

3. CONCRETE STEPS: Define 3-7 specific actionable steps using only the available tools

4. EVALUATION: Rate this approach on:
   - Feasibility (0-1): How doable is this?
   - Completeness (0-1): How thoroughly does this solve the problem?
   - Tool_fit (0-1): How well do available tools support this?
   - Innovation (0-1): How creative/novel is this approach?
   - Risk_level (0-1): How risky is this approach? (lower is safer)

5. RISKS & MITIGATIONS: List 2-3 things that could go wrong and how to handle them

Return your response as valid JSON:
{
  "thought_processes": [
    {
      "id": "systematic_approach_1",
      "name": "Systematic Method",
      "description": "Step-by-step methodical approach...",
      "reasoning_chain": [
        {
          "branch": "problem_analysis",
          "thoughts": ["What exactly needs to be solved?", "What are the constraints?"],
          "conclusion": "The main challenge is..."
        },
        {
          "branch": "solution_exploration",
          "thoughts": ["What options do I have?", "What has worked before?"],
          "conclusion": "The best path forward is..."
        }
      ],
      "steps": [
        {
          "step_number": 1,
          "action": "analyze_requirements",
          "tools": ["grep_search", "file_search"],
          "description": "Understand what needs to be built",
          "expected_outcome": "Clear requirements document"
        }
      ],
      "evaluation": {
        "feasibility": 0.9,
        "completeness": 0.8,
        "tool_fit": 0.9,
        "innovation": 0.6,
        "risk_level": 0.3
      },
      "confidence": 0.85,
      "risks": ["May be slow", "Could miss edge cases"],
      "mitigations": ["Set time limits", "Include testing phase"]
    }
  ],
  "meta_analysis": {
    "diversity_score": "How different are the approaches from each other?",
    "coverage_analysis": "What aspects of the problem are well covered?",
    "recommendation": {
      "best_approach_id": "systematic_approach_1",
      "reasoning": "Why this approach is recommended",
      "confidence": 0.85,
      "backup_approach": "What's the second best option?"
    }
  }
}

CRITICAL: Make each approach genuinely different. Don't just vary the steps - vary the fundamental thinking and philosophy behind each approach.
]],
    num_thoughts,
    task,
    tools_str
  )
end

---Parse the LLM's tree of thoughts response
---@param response_json string JSON response from LLM
---@return table|nil Parsed thought processes and meta-analysis
local function parse_tree_of_thoughts_response(response_json)
  local success, parsed = pcall(vim.json.decode, response_json)

  if not success then
    log:error("[Agent] Failed to parse tree of thoughts JSON: %s", response_json)
    return nil
  end

  if not parsed.thought_processes or #parsed.thought_processes == 0 then
    log:error("[Agent] No thought processes found in response")
    return nil
  end

  -- Validate and enhance each thought process
  for i, thought in ipairs(parsed.thought_processes) do
    -- Calculate overall confidence if not provided
    if not thought.confidence and thought.evaluation then
      local eval = thought.evaluation
      thought.confidence = (
        (eval.feasibility or 0) * 0.3
        + (eval.completeness or 0) * 0.3
        + (eval.tool_fit or 0) * 0.2
        + (eval.innovation or 0) * 0.1
        + (1 - (eval.risk_level or 0)) * 0.1
      )
    end

    -- Ensure required fields exist
    thought.id = thought.id or fmt("approach_%d", i)
    thought.name = thought.name or fmt("Approach %d", i)
    thought.risks = thought.risks or {}
    thought.mitigations = thought.mitigations or {}
  end

  return parsed
end

---Select the best approach from tree of thoughts analysis
---@param analysis table Parsed tree of thoughts response
---@return TreeOfThoughtsPath|nil Selected approach
local function select_best_approach(analysis)
  if not analysis or not analysis.thought_processes then
    return nil
  end

  -- If meta-analysis provides recommendation, use it
  if analysis.meta_analysis and analysis.meta_analysis.recommendation then
    local rec_id = analysis.meta_analysis.recommendation.best_approach_id
    for _, thought in ipairs(analysis.thought_processes) do
      if thought.id == rec_id then
        return thought
      end
    end
  end

  -- Fallback: select highest confidence approach
  local best = nil
  local best_score = 0

  for _, thought in ipairs(analysis.thought_processes) do
    local score = thought.confidence or 0
    if score > best_score then
      best_score = score
      best = thought
    end
  end

  return best
end

-- ============================================================================
-- PLAN EXECUTION FUNCTIONS
-- ============================================================================

---Prepare arguments for a specific tool based on step context
---@param tool_name string Name of the tool
---@param step table Current step being executed
---@param plan AgentPlan The overall plan
---@return table|nil Tool arguments
local function prepare_tool_arguments(tool_name, step, plan)
  local task = plan.task or ""
  local action = step.action or ""
  local description = step.description or ""

  if tool_name == "web_search" then
    return {
      query = extract_key_terms(task .. " " .. description),
      include_domains = {},
    }
  elseif tool_name == "grep_search" then
    return {
      query = extract_key_terms(action .. " " .. description),
      include_pattern = "**/*",
    }
  elseif tool_name == "file_search" then
    return {
      query = "**/*",
    }
  elseif tool_name == "read_file" then
    return {
      filepath = "README.md", -- Could be smarter about file selection
      start_line_number_base_zero = 0,
      end_line_number_base_zero = -1,
    }
  elseif tool_name == "create_file" then
    return {
      filepath = generate_filename(step, plan),
      content = generate_file_content(step, plan),
    }
  elseif tool_name == "insert_edit_into_file" then
    return {
      filepath = "generated_file.lua",
      explanation = fmt("Step %d: %s", step.step_number, step.description),
      code = generate_code_content(step, plan),
    }
  elseif tool_name == "cmd_runner" then
    return {
      cmd = generate_command(step, plan),
      flag = step.action:match("test") and "testing" or nil,
    }
  end

  return nil
end

---Execute a single step from the plan
---@param step table The step to execute
---@param plan AgentPlan The plan being executed
---@param chat table Chat context for tool access
---@return table Execution result
local function execute_plan_step(step, plan, chat)
  local result = {
    success = false,
    step_number = step.step_number,
    action = step.action,
    tools_attempted = {},
    outputs = {},
    errors = {},
    execution_time = os.time(),
  }

  -- Execute each tool specified in the step
  for _, tool_name in ipairs(step.tools or {}) do
    local tool_result = {
      tool = tool_name,
      success = false,
      output = nil,
      error = nil,
    }

    -- Check if tool is available
    if not chat.tools or not chat.tools.in_use[tool_name] then
      tool_result.error = fmt("Tool '%s' not available", tool_name)
    else
      -- Prepare tool arguments based on step context
      local args = prepare_tool_arguments(tool_name, step, plan)
      if args then
        tool_result.success = true
        tool_result.args = args
        tool_result.output = fmt("Prepared %s with args for: %s", tool_name, step.description)
      else
        tool_result.error = fmt("Could not prepare arguments for %s", tool_name)
      end
    end

    table.insert(result.tools_attempted, tool_result)

    if tool_result.success then
      table.insert(result.outputs, tool_result.output)
    else
      table.insert(result.errors, tool_result.error)
    end
  end

  -- Determine overall step success
  result.success = #result.errors == 0

  return result
end

-- ============================================================================
-- REFLECTION FUNCTIONS
-- ============================================================================

---Perform tree of thoughts reflection on plan execution
---@param plan AgentPlan Plan to reflect on
---@param state AgentState Current agent state
---@return table Reflection results with potential refinements
local function perform_plan_reflection(plan, state)
  local execution_state = plan.execution_state or {}
  local steps_completed = execution_state.completed_steps or 0
  local steps_failed = execution_state.failed_steps or 0
  local total_steps = #(plan.steps or {})

  -- Generate reflection paths using tree of thoughts
  local reflection_approaches = {
    {
      id = "performance_focus",
      name = "Performance Optimization",
      focus = "Improve success rate and efficiency",
      analysis = analyze_performance_issues(plan),
      refinements = generate_performance_refinements(plan),
    },
    {
      id = "completeness_focus",
      name = "Completeness Enhancement",
      focus = "Ensure comprehensive problem coverage",
      analysis = analyze_completeness_gaps(plan),
      refinements = generate_completeness_refinements(plan),
    },
    {
      id = "innovation_focus",
      name = "Innovation Opportunities",
      focus = "Find creative improvements and optimizations",
      analysis = analyze_innovation_potential(plan),
      refinements = generate_innovation_refinements(plan),
    },
  }

  -- Select best reflection approach
  local best_reflection = select_best_reflection(reflection_approaches)

  return {
    reflection_approaches = reflection_approaches,
    selected_approach = best_reflection,
    refinements_suggested = best_reflection and best_reflection.refinements or {},
    analysis_summary = best_reflection and best_reflection.analysis or {},
    reflection_confidence = best_reflection and calculate_reflection_confidence(best_reflection) or 0,
  }
end

-- ============================================================================
-- STATE MANAGEMENT
-- ============================================================================

---Get or create agent state for a chat session
---@param chat table Chat context
---@return AgentState
local function get_agent_state(chat)
  if not chat._tree_of_thoughts_state then
    chat._tree_of_thoughts_state = AgentState.new()
  end
  return chat._tree_of_thoughts_state
end

---Get list of available tools from chat context
---@param chat table Chat context
---@return string[] Array of tool names
local function get_available_tools(chat)
  local tools = {}

  if chat and chat.tools and chat.tools.in_use then
    for tool_name, _ in pairs(chat.tools.in_use) do
      if tool_name ~= "agent" then -- Don't include self
        table.insert(tools, tool_name)
      end
    end
  else
    -- Fallback to common tools
    tools = {
      "web_search",
      "grep_search",
      "file_search",
      "read_file",
      "create_file",
      "insert_edit_into_file",
      "cmd_runner",
      "get_changed_files",
    }
  end

  return tools
end

-- ============================================================================
-- MODE IMPLEMENTATIONS
-- ============================================================================

---REASON MODE: Generate tree of thoughts analysis and create execution plan
---@param args table Arguments (task, num_thoughts, confidence_threshold)
---@param chat table Chat context
---@return table Result with plan or error
local function process_reason_mode(args, chat)
  local task = args.task
  local num_thoughts = args.num_thoughts or 4
  local confidence_threshold = args.confidence_threshold or 0.8

  -- Validate inputs
  if not task or type(task) ~= "string" or task:len() == 0 then
    return {
      status = "error",
      data = "Task must be a non-empty string",
    }
  end

  if num_thoughts < 2 or num_thoughts > 10 then
    return {
      status = "error",
      data = "num_thoughts must be between 2 and 10",
    }
  end

  local state = get_agent_state(chat)
  local available_tools = get_available_tools(chat)

  log:info("[Agent] Starting tree of thoughts reasoning for: %s", task)

  -- Generate tree of thoughts prompt
  local prompt = create_tree_of_thoughts_prompt(task, available_tools, num_thoughts)

  -- For now, simulate LLM response with a structured example
  -- In real implementation, this would call the LLM with the prompt
  local simulated_response = generate_example_tree_of_thoughts(task, available_tools, num_thoughts)

  -- Parse the response
  local analysis = parse_tree_of_thoughts_response(vim.json.encode(simulated_response))
  if not analysis then
    return {
      status = "error",
      data = "Failed to generate valid tree of thoughts analysis",
    }
  end

  -- Select best approach
  local best_approach = select_best_approach(analysis)
  if not best_approach or best_approach.confidence < confidence_threshold then
    return {
      status = "error",
      data = {
        error_type = "insufficient_confidence",
        message = "No approach meets confidence threshold",
        best_confidence = best_approach and best_approach.confidence or 0,
        threshold = confidence_threshold,
        approaches_considered = #analysis.thought_processes,
      },
    }
  end

  -- Create execution plan
  local plan_id = fmt("tot_plan_%d_%d", os.time(), math.random(1000, 9999))
  local plan = {
    id = plan_id,
    task = task,
    created_at = os.date("%Y-%m-%d %H:%M:%S"),
    status = "created",
    approach_name = best_approach.name,
    confidence = best_approach.confidence,
    steps = best_approach.steps,
    all_thought_processes = analysis.thought_processes,
    selected_thought_id = best_approach.id,
    execution_state = {
      step_index = 1,
      completed_steps = 0,
      failed_steps = 0,
      step_results = {},
    },
    reflection_history = {},
  }

  -- Store plan
  state.active_plans[plan_id] = plan

  -- Record reasoning session
  table.insert(state.reasoning_sessions, {
    task = task,
    timestamp = os.time(),
    approaches_generated = #analysis.thought_processes,
    selected_approach = best_approach.id,
    confidence = best_approach.confidence,
    plan_id = plan_id,
  })

  log:info(
    "[Agent] Created plan %s with approach '%s' (confidence: %.2f)",
    plan_id,
    best_approach.name,
    best_approach.confidence
  )

  return {
    status = "success",
    data = {
      phase = "reasoning_complete",
      plan = plan,
      analysis = analysis,
      tree_of_thoughts_prompt = prompt,
    },
  }
end

---EXECUTE MODE: Execute the next step of a plan
---@param args table Arguments (plan_id)
---@param chat table Chat context
---@return table Execution result
local function process_execute_mode(args, chat)
  local plan_id = args.plan_id

  if not plan_id then
    return {
      status = "error",
      data = "plan_id is required",
    }
  end

  local state = get_agent_state(chat)
  local plan = state.active_plans[plan_id]

  if not plan then
    return {
      status = "error",
      data = fmt("Plan '%s' not found", plan_id),
    }
  end

  local execution_state = plan.execution_state
  local steps = plan.steps or {}

  -- Check if execution is complete
  if execution_state.step_index > #steps then
    plan.status = "completed"
    plan.completed_at = os.date("%Y-%m-%d %H:%M:%S")

    return {
      status = "success",
      data = {
        phase = "execution_complete",
        plan = plan,
        summary = {
          total_steps = #steps,
          completed = execution_state.completed_steps,
          failed = execution_state.failed_steps,
          success_rate = execution_state.completed_steps / #steps,
        },
      },
    }
  end

  -- Execute current step
  local current_step = steps[execution_state.step_index]
  local step_result = execute_plan_step(current_step, plan, chat)

  -- Update execution state
  execution_state.step_results[execution_state.step_index] = step_result
  if step_result.success then
    execution_state.completed_steps = execution_state.completed_steps + 1
  else
    execution_state.failed_steps = execution_state.failed_steps + 1
  end
  execution_state.step_index = execution_state.step_index + 1

  -- Update plan status
  plan.status = "executing"

  -- Log execution
  table.insert(state.execution_logs, {
    plan_id = plan_id,
    step_number = current_step.step_number,
    success = step_result.success,
    timestamp = os.time(),
  })

  log:info(
    "[Agent] Executed step %d/%d for plan %s (Success: %s)",
    current_step.step_number,
    #steps,
    plan_id,
    step_result.success
  )

  return {
    status = "success",
    data = {
      phase = "step_executed",
      plan = plan,
      step_result = step_result,
      progress = {
        current_step = execution_state.step_index - 1,
        total_steps = #steps,
        completed = execution_state.completed_steps,
        failed = execution_state.failed_steps,
        next_step = execution_state.step_index <= #steps and steps[execution_state.step_index] or nil,
      },
    },
  }
end

---REFLECT MODE: Analyze execution and refine plan using tree of thoughts
---@param args table Arguments (plan_id)
---@param chat table Chat context
---@return table Reflection result
local function process_reflect_mode(args, chat)
  local plan_id = args.plan_id

  if not plan_id then
    return {
      status = "error",
      data = "plan_id is required",
    }
  end

  local state = get_agent_state(chat)
  local plan = state.active_plans[plan_id]

  if not plan then
    return {
      status = "error",
      data = fmt("Plan '%s' not found", plan_id),
    }
  end

  -- Perform tree of thoughts reflection
  local reflection_result = perform_plan_reflection(plan, state)

  -- Apply refinements if confidence is high
  local refinements_applied = 0
  if reflection_result.reflection_confidence > 0.7 then
    refinements_applied = apply_plan_refinements(plan, reflection_result.refinements_suggested)
  end

  -- Update plan
  plan.status = "reflected"
  plan.reflected_at = os.date("%Y-%m-%d %H:%M:%S")
  table.insert(plan.reflection_history, reflection_result)

  -- Record reflection
  table.insert(state.reflection_results, {
    plan_id = plan_id,
    timestamp = os.time(),
    approaches_considered = #reflection_result.reflection_approaches,
    refinements_applied = refinements_applied,
  })

  log:info("[Agent] Reflected on plan %s (Refinements applied: %d)", plan_id, refinements_applied)

  return {
    status = "success",
    data = {
      phase = "reflection_complete",
      plan = plan,
      reflection = reflection_result,
      refinements_applied = refinements_applied,
    },
  }
end

-- ============================================================================
-- TOOL INTERFACE
-- ============================================================================

return {
  name = "agent",
  cmds = {
    function(self, args, input)
      if not args or type(args) ~= "table" then
        return {
          status = "error",
          data = "Invalid arguments provided",
        }
      end

      local mode = args.mode or "reason"
      local chat = self.chat

      if mode == "reason" then
        return process_reason_mode(args, chat)
      elseif mode == "execute" then
        return process_execute_mode(args, chat)
      elseif mode == "reflect" then
        return process_reflect_mode(args, chat)
      else
        return {
          status = "error",
          data = fmt("Unknown mode: %s", mode),
        }
      end
    end,
  },
  schema = {
    ["function"] = {
      name = "agent",
      description = "Tree of Thoughts AI agent that generates multiple solution approaches, evaluates them, and executes the best one through deliberate reasoning",
      parameters = {
        type = "object",
        properties = {
          mode = {
            type = "string",
            enum = { "reason", "execute", "reflect" },
            description = "Operation mode: 'reason' for tree of thoughts analysis, 'execute' for step execution, 'reflect' for plan refinement",
          },
          task = {
            type = "string",
            description = "The problem to solve (required for reason mode)",
          },
          num_thoughts = {
            type = "number",
            description = "Number of thought processes to generate (2-10, default: 4)",
          },
          confidence_threshold = {
            type = "number",
            description = "Minimum confidence required to proceed (0-1, default: 0.8)",
          },
          plan_id = {
            type = "string",
            description = "Plan identifier (required for execute and reflect modes)",
          },
        },
        required = { "mode" },
      },
    },
    type = "function",
  },
  handlers = {
    on_exit = function(agent)
      log:trace("[Agent] Cleanup completed")
    end,
  },
  output = {
    prompt = function(self, agent)
      local args = self.args
      local mode = args.mode or "reason"

      if mode == "reason" then
        return fmt("Generate tree of thoughts analysis for: %s?", args.task or "unknown task")
      elseif mode == "execute" then
        return fmt("Execute next step of plan %s?", args.plan_id or "unknown")
      elseif mode == "reflect" then
        return fmt("Perform tree of thoughts reflection on plan %s?", args.plan_id or "unknown")
      end

      return "Execute tree of thoughts agent?"
    end,

    success = function(self, agent, cmd, stdout)
      local data = stdout[1]

      if type(data) == "table" and data.phase == "reasoning_complete" then
        local plan = data.plan
        local analysis = data.analysis

        local output = fmt(
          [[<agentTool>🧠 **Tree of Thoughts Agent - Analysis Complete**

**Task:** %s
**Selected Approach:** %s (Confidence: %.1f%%)
**Thought Processes Considered:** %d

**📋 Execution Plan Created:**
- **Plan ID:** `%s`
- **Steps:** %d
- **Estimated Success Rate:** %.1f%%

**Tree of Thoughts Analysis:**
%s

**Next:** Use execute mode with plan_id: `%s`</agentTool>]],
          plan.task,
          plan.approach_name,
          plan.confidence * 100,
          #(analysis.thought_processes or {}),
          plan.id,
          #plan.steps,
          plan.confidence * 100,
          generate_analysis_summary(analysis),
          plan.id
        )

        local user_msg = output:gsub("<agentTool>", ""):gsub("</agentTool>", "")
        agent.chat:add_tool_output(self, output, user_msg)
      elseif type(data) == "table" and data.phase == "step_executed" then
        local step_result = data.step_result
        local progress = data.progress

        local status_icon = step_result.success and "✅" or "❌"
        local output = fmt(
          [[<agentTool>%s **Tree of Thoughts Agent - Step Executed**

**Step %d/%d:** %s
**Status:** %s
**Tools Used:** %s

**Progress:** %d completed, %d failed
**Next:** %s</agentTool>]],
          status_icon,
          progress.current_step,
          progress.total_steps,
          step_result.action,
          step_result.success and "Success" or "Failed",
          table.concat(step_result.tools_attempted or {}, ", "),
          progress.completed,
          progress.failed,
          progress.next_step and fmt("Step %d: %s", progress.current_step + 1, progress.next_step.action)
            or "Execution complete"
        )

        local user_msg = output:gsub("<agentTool>", ""):gsub("</agentTool>", "")
        agent.chat:add_tool_output(self, output, user_msg)
      else
        local output = fmt("<agentTool>🤖 Tree of Thoughts Agent: %s</agentTool>", vim.inspect(data))
        local user_msg = output:gsub("<agentTool>", ""):gsub("</agentTool>", "")
        agent.chat:add_tool_output(self, output, user_msg)
      end
    end,

    error = function(self, agent, cmd, stderr)
      local errors = table.concat(stderr, "\n")
      local output = fmt("<agentTool>❌ **Tree of Thoughts Agent Error:** %s</agentTool>", errors)
      agent.chat:add_tool_output(self, output)
    end,

    rejected = function(self, agent, cmd)
      agent.chat:add_tool_output(self, "**Tree of Thoughts Agent:** Operation cancelled by user")
    end,
  },
}

